<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\User;
use App\Models\PriceList;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $firstUser = User::first();
        $priceList = PriceList::first();

        $customers = [
            [
                'type' => 'b2b',
                'company_name' => 'TechCorp International',
                'email' => 'contact@techcorp.com',
                'tax_id' => 'TC-12345678',
                'phone' => '+1-555-0101',
                'shipping_address' => '123 Tech Street',
                'billing_address' => '123 Tech Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94102',
                'country' => 'USA',
                'payment_terms' => 30,
                'credit_limit' => 50000.00,
                'region' => 'North America',
                'category' => 'Technology',
                'account_group' => 'Enterprise',
                'assigned_sales_rep' => $firstUser?->id,
                'price_list_id' => $priceList?->id,
                'is_active' => true,
            ],
            [
                'type' => 'b2b',
                'company_name' => 'Global Manufacturing Ltd',
                'email' => 'sales@globalmanuf.com',
                'tax_id' => 'GM-87654321',
                'phone' => '+44-20-7123-4567',
                'shipping_address' => '456 Industry Road',
                'billing_address' => '456 Industry Road',
                'city' => 'London',
                'postal_code' => 'SW1A 1AA',
                'country' => 'United Kingdom',
                'payment_terms' => 60,
                'credit_limit' => 100000.00,
                'region' => 'Europe',
                'category' => 'Manufacturing',
                'account_group' => 'Enterprise',
                'assigned_sales_rep' => $firstUser?->id,
                'price_list_id' => $priceList?->id,
                'is_active' => true,
            ],
            [
                'type' => 'b2c',
                'first_name' => 'John',
                'last_name' => 'Smith',
                'email' => 'john.smith@email.com',
                'phone' => '+1-555-0102',
                'shipping_address' => '789 Residential Ave',
                'billing_address' => '789 Residential Ave',
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10001',
                'country' => 'USA',
                'payment_terms' => 0,
                'credit_limit' => 5000.00,
                'region' => 'North America',
                'category' => 'Individual',
                'account_group' => 'Retail',
                'is_active' => true,
            ],
            [
                'type' => 'b2b',
                'company_name' => 'EuroTech Solutions',
                'email' => 'info@eurotech.eu',
                'tax_id' => 'ET-11223344',
                'phone' => '+49-30-12345678',
                'shipping_address' => '321 Berlin Strasse',
                'billing_address' => '321 Berlin Strasse',
                'city' => 'Berlin',
                'postal_code' => '10115',
                'country' => 'Germany',
                'payment_terms' => 45,
                'credit_limit' => 75000.00,
                'region' => 'Europe',
                'category' => 'Technology',
                'account_group' => 'Corporate',
                'assigned_sales_rep' => $firstUser?->id,
                'price_list_id' => $priceList?->id,
                'is_active' => true,
            ],
            [
                'type' => 'b2c',
                'first_name' => 'Maria',
                'last_name' => 'Garcia',
                'email' => 'maria.garcia@email.com',
                'phone' => '+34-91-123-4567',
                'shipping_address' => '654 Madrid Street',
                'billing_address' => '654 Madrid Street',
                'city' => 'Madrid',
                'postal_code' => '28001',
                'country' => 'Spain',
                'payment_terms' => 0,
                'credit_limit' => 3000.00,
                'region' => 'Europe',
                'category' => 'Individual',
                'account_group' => 'Retail',
                'is_active' => true,
            ],
            [
                'type' => 'b2b',
                'company_name' => 'Asian Trading Co',
                'email' => 'contact@asiantrade.jp',
                'tax_id' => 'AT-99887766',
                'phone' => '+81-3-1234-5678',
                'shipping_address' => '999 Tokyo Boulevard',
                'billing_address' => '999 Tokyo Boulevard',
                'city' => 'Tokyo',
                'postal_code' => '100-0001',
                'country' => 'Japan',
                'payment_terms' => 30,
                'credit_limit' => 60000.00,
                'region' => 'Asia',
                'category' => 'Trading',
                'account_group' => 'Corporate',
                'assigned_sales_rep' => $firstUser?->id,
                'price_list_id' => $priceList?->id,
                'is_active' => true,
            ],
            [
                'type' => 'b2b',
                'company_name' => 'Australian Suppliers Pty',
                'email' => 'sales@aussupply.au',
                'tax_id' => 'AS-55443322',
                'phone' => '+61-2-9876-5432',
                'shipping_address' => '147 Sydney Road',
                'billing_address' => '147 Sydney Road',
                'city' => 'Sydney',
                'postal_code' => '2000',
                'country' => 'Australia',
                'payment_terms' => 30,
                'credit_limit' => 40000.00,
                'region' => 'Oceania',
                'category' => 'Wholesale',
                'account_group' => 'Corporate',
                'assigned_sales_rep' => $firstUser?->id,
                'price_list_id' => $priceList?->id,
                'is_active' => true,
            ],
            [
                'type' => 'b2c',
                'first_name' => 'Ahmed',
                'last_name' => 'Hassan',
                'email' => 'ahmed.hassan@email.com',
                'phone' => '+971-4-123-4567',
                'shipping_address' => '258 Dubai Marina',
                'billing_address' => '258 Dubai Marina',
                'city' => 'Dubai',
                'postal_code' => '00000',
                'country' => 'UAE',
                'payment_terms' => 0,
                'credit_limit' => 10000.00,
                'region' => 'Middle East',
                'category' => 'Individual',
                'account_group' => 'Premium',
                'is_active' => true,
            ],
            [
                'type' => 'b2b',
                'company_name' => 'Canadian Enterprises Inc',
                'email' => 'info@canent.ca',
                'tax_id' => 'CE-66778899',
                'phone' => '+1-416-555-0103',
                'shipping_address' => '369 Toronto Street',
                'billing_address' => '369 Toronto Street',
                'city' => 'Toronto',
                'state' => 'ON',
                'postal_code' => 'M5H 2N2',
                'country' => 'Canada',
                'payment_terms' => 30,
                'credit_limit' => 55000.00,
                'region' => 'North America',
                'category' => 'Services',
                'account_group' => 'Corporate',
                'assigned_sales_rep' => $firstUser?->id,
                'price_list_id' => $priceList?->id,
                'is_active' => true,
            ],
            [
                'type' => 'b2c',
                'first_name' => 'Sophie',
                'last_name' => 'Dubois',
                'email' => 'sophie.dubois@email.com',
                'phone' => '+33-1-23-45-67-89',
                'shipping_address' => '741 Paris Avenue',
                'billing_address' => '741 Paris Avenue',
                'city' => 'Paris',
                'postal_code' => '75001',
                'country' => 'France',
                'payment_terms' => 0,
                'credit_limit' => 4000.00,
                'region' => 'Europe',
                'category' => 'Individual',
                'account_group' => 'Retail',
                'is_active' => true,
            ],
        ];

        foreach ($customers as $customer) {
            Customer::create($customer);
        }
    }
}
