<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use App\Models\Unit;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();
        $units = Unit::all();
        $suppliers = Supplier::all();

        $products = [
            [
                'name' => 'Laptop Computer Dell XPS 15',
                'slug' => 'laptop-computer-dell-xps-15',
                'short_description' => 'High-performance laptop for business professionals',
                'description' => 'Dell XPS 15 with Intel Core i7, 16GB RAM, 512GB SSD, 15.6" 4K display',
                'category_id' => $categories->where('name', 'IT Hardware')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'PCS')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 1599.99,
                'cost_price' => 1200.00,
                'currency' => 'USD',
                'current_stock' => 25,
                'reorder_level' => 5,
                'reorder_quantity' => 10,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->first()?->id,
                'brand' => 'Dell',
                'manufacturer' => 'Dell Technologies',
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_featured' => true,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'tags' => ['featured', 'bestseller'],
            ],
            [
                'name' => 'Office Chair Ergonomic Pro',
                'slug' => 'office-chair-ergonomic-pro',
                'short_description' => 'Comfortable ergonomic office chair',
                'description' => 'Premium ergonomic office chair with lumbar support, adjustable armrests, and breathable mesh back',
                'category_id' => $categories->where('name', 'Furniture')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'PCS')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 299.99,
                'cost_price' => 180.00,
                'currency' => 'USD',
                'current_stock' => 50,
                'reorder_level' => 10,
                'reorder_quantity' => 20,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->where('company_name', 'LIKE', '%Furniture%')->first()?->id,
                'brand' => 'ErgoComfort',
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'tags' => ['new', 'ergonomic'],
            ],
            [
                'name' => 'A4 Printer Paper - 500 Sheets',
                'slug' => 'a4-printer-paper-500-sheets',
                'short_description' => 'Premium white A4 paper, 80gsm',
                'description' => 'High-quality A4 printing paper, ideal for office use, 80gsm weight',
                'category_id' => $categories->where('name', 'Office Supplies')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'PACK')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 8.99,
                'cost_price' => 5.50,
                'currency' => 'USD',
                'current_stock' => 200,
                'reorder_level' => 50,
                'reorder_quantity' => 100,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->where('company_name', 'LIKE', '%Office%')->first()?->id,
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'tags' => ['office', 'supplies'],
            ],
            [
                'name' => 'Steel Sheet 1mm',
                'slug' => 'steel-sheet-1mm',
                'short_description' => 'Cold-rolled steel sheet, 1mm thickness',
                'description' => 'Industrial-grade cold-rolled steel sheet, 1mm thickness, suitable for manufacturing',
                'category_id' => $categories->where('name', 'Raw Materials')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'SQM')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 45.00,
                'cost_price' => 32.00,
                'currency' => 'USD',
                'current_stock' => 150,
                'reorder_level' => 30,
                'reorder_quantity' => 50,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->where('company_name', 'LIKE', '%Raw%')->first()?->id,
                'manufacturer' => 'SteelCorp',
                'weight' => 7.85,
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_active' => true,
                'is_available_for_purchase' => true,
            ],
            [
                'name' => 'Safety Helmet Construction Grade',
                'slug' => 'safety-helmet-construction-grade',
                'short_description' => 'Hard hat for construction sites',
                'description' => 'OSHA-compliant safety helmet with adjustable suspension, suitable for construction and industrial use',
                'category_id' => $categories->where('name', 'Safety Equipment')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'PCS')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 24.99,
                'cost_price' => 15.00,
                'currency' => 'USD',
                'current_stock' => 100,
                'reorder_level' => 20,
                'reorder_quantity' => 50,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->where('company_name', 'LIKE', '%Safety%')->first()?->id,
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'tags' => ['safety', 'ppe'],
            ],
            [
                'name' => 'IT Consulting Service - Hourly',
                'slug' => 'it-consulting-service-hourly',
                'short_description' => 'Professional IT consulting services',
                'description' => 'Expert IT consulting and technical support services, billed hourly',
                'category_id' => $categories->where('name', 'Software Licenses')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'HOUR')->first()?->id ?? $units->first()?->id,
                'type' => 'service',
                'base_price' => 120.00,
                'cost_price' => 80.00,
                'currency' => 'USD',
                'track_inventory' => false,
                'primary_supplier_id' => $suppliers->where('type', 'service')->first()?->id,
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'tags' => ['service', 'consulting'],
            ],
            [
                'name' => 'Cardboard Boxes - Medium (10 pack)',
                'slug' => 'cardboard-boxes-medium-10-pack',
                'short_description' => 'Medium-sized shipping boxes',
                'description' => 'Durable cardboard shipping boxes, 40x30x30cm, pack of 10',
                'category_id' => $categories->where('name', 'Packaging Materials')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'PACK')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 19.99,
                'cost_price' => 12.00,
                'currency' => 'USD',
                'current_stock' => 300,
                'reorder_level' => 100,
                'reorder_quantity' => 200,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->where('company_name', 'LIKE', '%Packaging%')->first()?->id,
                'length' => 40,
                'width' => 30,
                'height' => 30,
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'is_on_sale' => true,
                'sale_price' => 15.99,
                'sale_start_date' => now(),
                'sale_end_date' => now()->addMonth(),
                'tags' => ['seasonal', 'sale'],
            ],
            [
                'name' => 'Power Drill Cordless 18V',
                'slug' => 'power-drill-cordless-18v',
                'short_description' => 'Professional cordless power drill',
                'description' => '18V lithium-ion cordless drill with 2 batteries, charger, and carrying case',
                'category_id' => $categories->where('name', 'Tools & Equipment')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'SET')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 159.99,
                'cost_price' => 95.00,
                'currency' => 'USD',
                'current_stock' => 40,
                'reorder_level' => 10,
                'reorder_quantity' => 20,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->where('company_name', 'LIKE', '%Tools%')->first()?->id,
                'brand' => 'PowerPro',
                'manufacturer' => 'PowerPro Industries',
                'weight' => 1.5,
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_featured' => true,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'tags' => ['featured', 'tools'],
            ],
            [
                'name' => 'Multi-Surface Cleaner - 5L',
                'slug' => 'multi-surface-cleaner-5l',
                'short_description' => 'Industrial strength cleaning solution',
                'description' => 'Professional multi-surface cleaner, concentrated formula, 5-liter container',
                'category_id' => $categories->where('name', 'Cleaning Supplies')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'L')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 34.99,
                'cost_price' => 22.00,
                'currency' => 'USD',
                'current_stock' => 80,
                'reorder_level' => 15,
                'reorder_quantity' => 30,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->where('company_name', 'LIKE', '%Cleaning%')->first()?->id,
                'weight' => 5.2,
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_active' => true,
                'is_available_for_purchase' => true,
            ],
            [
                'name' => 'Network Switch 24-Port Gigabit',
                'slug' => 'network-switch-24-port-gigabit',
                'short_description' => 'Managed gigabit ethernet switch',
                'description' => '24-port managed gigabit ethernet switch with VLAN support and PoE',
                'category_id' => $categories->where('name', 'IT Hardware')->first()?->id ?? $categories->first()?->id,
                'unit_id' => $units->where('code', 'PCS')->first()?->id ?? $units->first()?->id,
                'type' => 'physical',
                'base_price' => 449.99,
                'cost_price' => 320.00,
                'currency' => 'USD',
                'current_stock' => 15,
                'reorder_level' => 3,
                'reorder_quantity' => 5,
                'track_inventory' => true,
                'primary_supplier_id' => $suppliers->first()?->id,
                'brand' => 'NetGear Pro',
                'manufacturer' => 'NetGear',
                'is_taxable' => true,
                'tax_rate' => 10.00,
                'is_new' => true,
                'is_active' => true,
                'is_available_for_purchase' => true,
                'tags' => ['new', 'networking'],
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
