<?php

namespace Database\Seeders;

use App\Models\Supplier;
use App\Models\User;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $firstUser = User::first();

        $suppliers = [
            [
                'type' => 'manufacturer',
                'company_name' => 'Global Electronics Manufacturing',
                'email' => 'procurement@globalelec.com',
                'tax_id' => 'GEM-12345678',
                'phone' => '+86-21-1234-5678',
                'address' => '888 Manufacturing District',
                'city' => 'Shanghai',
                'postal_code' => '200000',
                'country' => 'China',
                'payment_terms' => 30,
                'website' => 'https://globalelec.com',
                'contact_person' => 'Wei Zhang',
                // 'contact_email' => 'wei.zhang@globalelec.com',
                // 'contact_phone' => '+86-21-1234-5679',
                'product_categories' => ['Electronics', 'Components'],
                'contract_number' => 'CNT-2025-001',
                'contract_start_date' => now()->subMonth(),
                'contract_end_date' => now()->addYear(),
                'performance_rating' => 4.5,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'distributor',
                'company_name' => 'Office Supplies Direct',
                'email' => 'sales@officesupplies.com',
                'tax_id' => 'OSD-87654321',
                'phone' => '+1-800-555-0104',
                'address' => '456 Distribution Center',
                'city' => 'Chicago',
                'state' => 'IL',
                'postal_code' => '60601',
                'country' => 'USA',
                'payment_terms' => 45,
                'website' => 'https://officesupplies.com',
                'contact_person' => 'Sarah Johnson',
                // 'contact_email' => 'sarah.j@officesupplies.com',
                // 'contact_phone' => '+1-800-555-0105',
                'product_categories' => ['Office Supplies', 'Stationery'],
                'contract_number' => 'CNT-2025-002',
                'contract_start_date' => now()->subMonths(2),
                'contract_end_date' => now()->addMonths(10),
                'performance_rating' => 4.8,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'service',
                'company_name' => 'TechSupport Solutions',
                'email' => 'contact@techsupport.com',
                'tax_id' => 'TSS-11223344',
                'phone' => '+44-20-7890-1234',
                'address' => '789 Service Lane',
                'city' => 'London',
                'postal_code' => 'EC1A 1BB',
                'country' => 'United Kingdom',
                'payment_terms' => 30,
                'website' => 'https://techsupport.com',
                'contact_person' => 'James Williams',
                // 'contact_email' => 'james.w@techsupport.com',
                // 'contact_phone' => '+44-20-7890-1235',
                'product_categories' => ['IT Services', 'Technical Support'],
                'performance_rating' => 4.2,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'manufacturer',
                'company_name' => 'Industrial Tools Corp',
                'email' => 'orders@indtools.com',
                'tax_id' => 'ITC-99887766',
                'phone' => '+49-89-1234-5678',
                'address' => '321 Industrial Park',
                'city' => 'Munich',
                'postal_code' => '80331',
                'country' => 'Germany',
                'payment_terms' => 60,
                'website' => 'https://indtools.com',
                'contact_person' => 'Hans Mueller',
                // 'contact_email' => 'h.mueller@indtools.com',
                // 'contact_phone' => '+49-89-1234-5679',
                'product_categories' => ['Tools', 'Equipment'],
                'contract_number' => 'CNT-2025-003',
                'contract_start_date' => now(),
                'contract_end_date' => now()->addYears(2),
                'performance_rating' => 4.7,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'distributor',
                'company_name' => 'Packaging Materials Inc',
                'email' => 'info@packmat.com',
                'tax_id' => 'PMI-55667788',
                'phone' => '+1-555-0106',
                'address' => '147 Warehouse Blvd',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'postal_code' => '90001',
                'country' => 'USA',
                'payment_terms' => 30,
                'website' => 'https://packmat.com',
                'contact_person' => 'Robert Chen',
                // 'contact_email' => 'r.chen@packmat.com',
                // 'contact_phone' => '+1-555-0107',
                'product_categories' => ['Packaging', 'Shipping Materials'],
                'performance_rating' => 4.4,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'manufacturer',
                'company_name' => 'Raw Materials Ltd',
                'email' => 'sales@rawmat.com',
                'tax_id' => 'RML-44556677',
                'phone' => '+61-3-1234-5678',
                'address' => '258 Industrial Estate',
                'city' => 'Melbourne',
                'postal_code' => '3000',
                'country' => 'Australia',
                'payment_terms' => 45,
                'website' => 'https://rawmat.com',
                'contact_person' => 'Emma Wilson',
                // 'contact_email' => 'e.wilson@rawmat.com',
                // 'contact_phone' => '+61-3-1234-5679',
                'product_categories' => ['Raw Materials', 'Metals'],
                'contract_number' => 'CNT-2025-004',
                'contract_start_date' => now()->subWeek(),
                'contract_end_date' => now()->addMonths(18),
                'performance_rating' => 4.6,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'service',
                'company_name' => 'Logistics Express',
                'email' => 'dispatch@logexpress.com',
                'tax_id' => 'LEX-33445566',
                'phone' => '+33-1-23-45-67-89',
                'address' => '963 Transport Hub',
                'city' => 'Paris',
                'postal_code' => '75002',
                'country' => 'France',
                'payment_terms' => 15,
                'website' => 'https://logexpress.com',
                'contact_person' => 'Pierre Dubois',
                // 'contact_email' => 'p.dubois@logexpress.com',
                // 'contact_phone' => '+33-1-23-45-67-90',
                'product_categories' => ['Logistics', 'Transportation'],
                'performance_rating' => 4.9,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'distributor',
                'company_name' => 'Safety Equipment Pro',
                'email' => 'orders@safetypro.com',
                'tax_id' => 'SEP-22334455',
                'phone' => '+1-555-0108',
                'address' => '741 Safety Drive',
                'city' => 'Houston',
                'state' => 'TX',
                'postal_code' => '77001',
                'country' => 'USA',
                'payment_terms' => 30,
                'website' => 'https://safetypro.com',
                'contact_person' => 'Michael Brown',
                // 'contact_email' => 'm.brown@safetypro.com',
                // 'contact_phone' => '+1-555-0109',
                'product_categories' => ['Safety Equipment', 'PPE'],
                'contract_number' => 'CNT-2025-005',
                'contract_start_date' => now()->subMonths(3),
                'contract_end_date' => now()->addMonths(9),
                'performance_rating' => 4.3,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'manufacturer',
                'company_name' => 'Furniture Factory International',
                'email' => 'export@furnfactory.com',
                'tax_id' => 'FFI-11998877',
                'phone' => '+39-02-1234-5678',
                'address' => '852 Manufacturing Zone',
                'city' => 'Milan',
                'postal_code' => '20121',
                'country' => 'Italy',
                'payment_terms' => 60,
                'website' => 'https://furnfactory.com',
                'contact_person' => 'Giovanni Rossi',
                // 'contact_email' => 'g.rossi@furnfactory.com',
                // 'contact_phone' => '+39-02-1234-5679',
                'product_categories' => ['Furniture', 'Office Equipment'],
                'contract_number' => 'CNT-2025-006',
                'contract_start_date' => now()->subDays(15),
                'contract_end_date' => now()->addYear(),
                'performance_rating' => 4.5,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
            [
                'type' => 'service',
                'company_name' => 'Cleaning Services Plus',
                'email' => 'admin@cleanplus.com',
                'tax_id' => 'CSP-66778899',
                'phone' => '+34-91-234-5678',
                'address' => '369 Service Center',
                'city' => 'Barcelona',
                'postal_code' => '08001',
                'country' => 'Spain',
                'payment_terms' => 30,
                'website' => 'https://cleanplus.com',
                'contact_person' => 'Ana Martinez',
                // 'contact_email' => 'a.martinez@cleanplus.com',
                // 'contact_phone' => '+34-91-234-5679',
                'product_categories' => ['Cleaning Services', 'Supplies'],
                'performance_rating' => 4.1,
                'assigned_procurement_officer' => $firstUser?->id,
                'is_approved' => true,
                'approved_by' => $firstUser?->id,
                'approved_at' => now(),
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::create($supplier);
        }
    }
}
