<?php

namespace Database\Seeders;

use App\Models\Warehouse;
use Illuminate\Database\Seeder;

class WarehouseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $warehouses = [
            [
                'name' => 'Main Distribution Center',
                'type' => 'main',
                'address' => '1234 Industrial Parkway',
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10001',
                'country' => 'United States',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'manager_name' => 'John Smith',
                'phone' => '+1-555-0101',
                'email' => 'john.smith@optimasphere.com',
                'storage_capacity' => 50000.00,
                'current_utilization' => 32500.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => true,
                'notes' => 'Primary distribution center serving the Northeast region. Equipped with climate control and 24/7 security.',
                'operating_hours' => [
                    'monday' => '08:00-18:00',
                    'tuesday' => '08:00-18:00',
                    'wednesday' => '08:00-18:00',
                    'thursday' => '08:00-18:00',
                    'friday' => '08:00-18:00',
                    'saturday' => '09:00-13:00',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'West Coast Regional Hub',
                'type' => 'regional',
                'address' => '5678 Pacific Boulevard',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'postal_code' => '90001',
                'country' => 'United States',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'manager_name' => 'Sarah Johnson',
                'phone' => '+1-555-0202',
                'email' => 'sarah.johnson@optimasphere.com',
                'storage_capacity' => 35000.00,
                'current_utilization' => 21000.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Regional hub for West Coast distribution. Features automated sorting systems and loading docks.',
                'operating_hours' => [
                    'monday' => '07:00-19:00',
                    'tuesday' => '07:00-19:00',
                    'wednesday' => '07:00-19:00',
                    'thursday' => '07:00-19:00',
                    'friday' => '07:00-19:00',
                    'saturday' => '08:00-14:00',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'Chicago Distribution Center',
                'type' => 'distribution',
                'address' => '9012 Commerce Drive',
                'city' => 'Chicago',
                'state' => 'IL',
                'postal_code' => '60601',
                'country' => 'United States',
                'latitude' => 41.8781,
                'longitude' => -87.6298,
                'manager_name' => 'Michael Brown',
                'phone' => '+1-555-0303',
                'email' => 'michael.brown@optimasphere.com',
                'storage_capacity' => 42000.00,
                'current_utilization' => 28350.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Strategic location for Midwest distribution. Handles high-volume cross-docking operations.',
                'operating_hours' => [
                    'monday' => '06:00-20:00',
                    'tuesday' => '06:00-20:00',
                    'wednesday' => '06:00-20:00',
                    'thursday' => '06:00-20:00',
                    'friday' => '06:00-20:00',
                    'saturday' => '08:00-16:00',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'Atlanta Storage Facility',
                'type' => 'storage',
                'address' => '3456 Peachtree Street',
                'city' => 'Atlanta',
                'state' => 'GA',
                'postal_code' => '30301',
                'country' => 'United States',
                'latitude' => 33.7490,
                'longitude' => -84.3880,
                'manager_name' => 'Emily Davis',
                'phone' => '+1-555-0404',
                'email' => 'emily.davis@optimasphere.com',
                'storage_capacity' => 25000.00,
                'current_utilization' => 15750.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Long-term storage facility for seasonal inventory. Temperature-controlled zones available.',
                'operating_hours' => [
                    'monday' => '08:00-17:00',
                    'tuesday' => '08:00-17:00',
                    'wednesday' => '08:00-17:00',
                    'thursday' => '08:00-17:00',
                    'friday' => '08:00-17:00',
                    'saturday' => 'Closed',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'Miami Transit Hub',
                'type' => 'transit',
                'address' => '7890 Port Drive',
                'city' => 'Miami',
                'state' => 'FL',
                'postal_code' => '33101',
                'country' => 'United States',
                'latitude' => 25.7617,
                'longitude' => -80.1918,
                'manager_name' => 'Robert Martinez',
                'phone' => '+1-555-0505',
                'email' => 'robert.martinez@optimasphere.com',
                'storage_capacity' => 18000.00,
                'current_utilization' => 9450.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Transit hub near port facilities for international shipments. Customs bonded warehouse.',
                'operating_hours' => [
                    'monday' => '24/7',
                    'tuesday' => '24/7',
                    'wednesday' => '24/7',
                    'thursday' => '24/7',
                    'friday' => '24/7',
                    'saturday' => '24/7',
                    'sunday' => '24/7',
                ],
            ],
            [
                'name' => 'Dallas Regional Warehouse',
                'type' => 'regional',
                'address' => '2345 Ranch Road',
                'city' => 'Dallas',
                'state' => 'TX',
                'postal_code' => '75201',
                'country' => 'United States',
                'latitude' => 32.7767,
                'longitude' => -96.7970,
                'manager_name' => 'Jennifer Wilson',
                'phone' => '+1-555-0606',
                'email' => 'jennifer.wilson@optimasphere.com',
                'storage_capacity' => 30000.00,
                'current_utilization' => 18900.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Serves Texas and surrounding states. Advanced inventory management system integrated.',
                'operating_hours' => [
                    'monday' => '07:00-18:00',
                    'tuesday' => '07:00-18:00',
                    'wednesday' => '07:00-18:00',
                    'thursday' => '07:00-18:00',
                    'friday' => '07:00-18:00',
                    'saturday' => '09:00-13:00',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'Seattle Distribution Point',
                'type' => 'distribution',
                'address' => '4567 Harbor Avenue',
                'city' => 'Seattle',
                'state' => 'WA',
                'postal_code' => '98101',
                'country' => 'United States',
                'latitude' => 47.6062,
                'longitude' => -122.3321,
                'manager_name' => 'David Anderson',
                'phone' => '+1-555-0707',
                'email' => 'david.anderson@optimasphere.com',
                'storage_capacity' => 22000.00,
                'current_utilization' => 13200.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Northwest distribution point with rail access. Eco-friendly facility with solar panels.',
                'operating_hours' => [
                    'monday' => '08:00-18:00',
                    'tuesday' => '08:00-18:00',
                    'wednesday' => '08:00-18:00',
                    'thursday' => '08:00-18:00',
                    'friday' => '08:00-18:00',
                    'saturday' => '10:00-14:00',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'Phoenix Storage Complex',
                'type' => 'storage',
                'address' => '6789 Desert Road',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'postal_code' => '85001',
                'country' => 'United States',
                'latitude' => 33.4484,
                'longitude' => -112.0740,
                'manager_name' => 'Lisa Thompson',
                'phone' => '+1-555-0808',
                'email' => 'lisa.thompson@optimasphere.com',
                'storage_capacity' => 28000.00,
                'current_utilization' => 14560.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => false,
                'is_primary' => false,
                'notes' => 'Primarily for storage. Limited outbound operations. Climate-controlled for sensitive goods.',
                'operating_hours' => [
                    'monday' => '08:00-16:00',
                    'tuesday' => '08:00-16:00',
                    'wednesday' => '08:00-16:00',
                    'thursday' => '08:00-16:00',
                    'friday' => '08:00-16:00',
                    'saturday' => 'Closed',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'Boston Regional Hub',
                'type' => 'regional',
                'address' => '8901 Harbor Street',
                'city' => 'Boston',
                'state' => 'MA',
                'postal_code' => '02101',
                'country' => 'United States',
                'latitude' => 42.3601,
                'longitude' => -71.0589,
                'manager_name' => 'Christopher Lee',
                'phone' => '+1-555-0909',
                'email' => 'christopher.lee@optimasphere.com',
                'storage_capacity' => 32000.00,
                'current_utilization' => 22400.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Serves New England region. Historic building renovated with modern warehouse technology.',
                'operating_hours' => [
                    'monday' => '07:00-17:00',
                    'tuesday' => '07:00-17:00',
                    'wednesday' => '07:00-17:00',
                    'thursday' => '07:00-17:00',
                    'friday' => '07:00-17:00',
                    'saturday' => '08:00-12:00',
                    'sunday' => 'Closed',
                ],
            ],
            [
                'name' => 'Denver Mountain Distribution',
                'type' => 'distribution',
                'address' => '1357 Mountain View Drive',
                'city' => 'Denver',
                'state' => 'CO',
                'postal_code' => '80201',
                'country' => 'United States',
                'latitude' => 39.7392,
                'longitude' => -104.9903,
                'manager_name' => 'Amanda White',
                'phone' => '+1-555-1010',
                'email' => 'amanda.white@optimasphere.com',
                'storage_capacity' => 26000.00,
                'current_utilization' => 16640.00,
                'is_active' => true,
                'accepts_inbound' => true,
                'accepts_outbound' => true,
                'is_primary' => false,
                'notes' => 'Mountain region distribution. High-altitude facility with specialized equipment.',
                'operating_hours' => [
                    'monday' => '08:00-17:00',
                    'tuesday' => '08:00-17:00',
                    'wednesday' => '08:00-17:00',
                    'thursday' => '08:00-17:00',
                    'friday' => '08:00-17:00',
                    'saturday' => 'Closed',
                    'sunday' => 'Closed',
                ],
            ],
        ];

        foreach ($warehouses as $warehouse) {
            Warehouse::create($warehouse);
        }
    }
}
