<?php

namespace Database\Seeders;

use App\Models\Warehouse;
use App\Models\WorkCenter;
use Illuminate\Database\Seeder;

class WorkCenterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mainWarehouse = Warehouse::where('code', 'WH001')->first();

        $workCenters = [
            [
                'name' => 'CNC Machining Center 1',
                'type' => 'machine',
                'description' => '3-axis CNC milling machine for precision metal parts',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 1, Bay A, Line 1',
                'capacity_per_day' => 16,
                'capacity_unit' => 'hours',
                'efficiency_percentage' => 85,
                'utilization_percentage' => 0,
                'cost_per_hour' => 75.00,
                'setup_time_minutes' => 30,
                'teardown_time_minutes' => 15,
                'minimum_batch_size' => 1,
                'maximum_batch_size' => 100,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 1,
                'capabilities' => ['milling', 'drilling', 'tapping', 'boring'],
                'certifications' => ['ISO 9001', 'AS9100'],
                'maintenance_due_date' => now()->addMonths(3),
            ],
            [
                'name' => 'CNC Machining Center 2',
                'type' => 'machine',
                'description' => '5-axis CNC milling machine for complex parts',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 1, Bay A, Line 2',
                'capacity_per_day' => 16,
                'capacity_unit' => 'hours',
                'efficiency_percentage' => 90,
                'utilization_percentage' => 0,
                'cost_per_hour' => 125.00,
                'setup_time_minutes' => 45,
                'teardown_time_minutes' => 20,
                'minimum_batch_size' => 1,
                'maximum_batch_size' => 50,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 1,
                'capabilities' => ['5-axis milling', 'complex geometry', 'precision'],
                'certifications' => ['ISO 9001', 'AS9100'],
                'maintenance_due_date' => now()->addMonths(2),
            ],
            [
                'name' => 'Welding Station 1',
                'type' => 'manual',
                'description' => 'MIG/TIG welding station for metal fabrication',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 1, Bay B, Station 1',
                'capacity_per_day' => 8,
                'capacity_unit' => 'hours',
                'efficiency_percentage' => 80,
                'utilization_percentage' => 0,
                'cost_per_hour' => 45.00,
                'setup_time_minutes' => 10,
                'teardown_time_minutes' => 10,
                'minimum_batch_size' => 1,
                'maximum_batch_size' => null,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 1,
                'capabilities' => ['MIG welding', 'TIG welding', 'spot welding'],
                'certifications' => ['AWS D1.1', 'ISO 9001'],
                'maintenance_due_date' => now()->addMonths(6),
            ],
            [
                'name' => 'Assembly Line A',
                'type' => 'assembly',
                'description' => 'Main assembly line for product assembly',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 2, Bay A',
                'capacity_per_day' => 200,
                'capacity_unit' => 'units',
                'efficiency_percentage' => 75,
                'utilization_percentage' => 0,
                'cost_per_hour' => 30.00,
                'setup_time_minutes' => 60,
                'teardown_time_minutes' => 30,
                'minimum_batch_size' => 10,
                'maximum_batch_size' => 500,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 4,
                'capabilities' => ['product assembly', 'sub-assembly', 'testing'],
                'certifications' => ['ISO 9001'],
                'maintenance_due_date' => now()->addMonths(1),
            ],
            [
                'name' => 'Quality Control Station',
                'type' => 'quality_control',
                'description' => 'Inspection and quality testing station',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 2, Bay C',
                'capacity_per_day' => 100,
                'capacity_unit' => 'units',
                'efficiency_percentage' => 95,
                'utilization_percentage' => 0,
                'cost_per_hour' => 40.00,
                'setup_time_minutes' => 5,
                'teardown_time_minutes' => 5,
                'minimum_batch_size' => 1,
                'maximum_batch_size' => null,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 2,
                'capabilities' => ['visual inspection', 'dimensional inspection', 'functional testing'],
                'certifications' => ['ISO 9001', 'ISO 17025'],
                'maintenance_due_date' => now()->addMonths(12),
            ],
            [
                'name' => 'Laser Cutting Machine',
                'type' => 'machine',
                'description' => 'Fiber laser cutting machine for sheet metal',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 1, Bay C, Line 1',
                'capacity_per_day' => 14,
                'capacity_unit' => 'hours',
                'efficiency_percentage' => 88,
                'utilization_percentage' => 0,
                'cost_per_hour' => 95.00,
                'setup_time_minutes' => 20,
                'teardown_time_minutes' => 10,
                'minimum_batch_size' => 1,
                'maximum_batch_size' => 200,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 1,
                'capabilities' => ['laser cutting', 'sheet metal', 'precision cutting'],
                'certifications' => ['ISO 9001', 'CE'],
                'maintenance_due_date' => now()->addMonths(4),
            ],
            [
                'name' => 'Paint Booth 1',
                'type' => 'manual',
                'description' => 'Spray paint booth with climate control',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 1, Bay D',
                'capacity_per_day' => 50,
                'capacity_unit' => 'units',
                'efficiency_percentage' => 70,
                'utilization_percentage' => 0,
                'cost_per_hour' => 55.00,
                'setup_time_minutes' => 30,
                'teardown_time_minutes' => 45,
                'minimum_batch_size' => 5,
                'maximum_batch_size' => 100,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 2,
                'capabilities' => ['spray painting', 'powder coating', 'surface preparation'],
                'certifications' => ['EPA Compliant', 'OSHA'],
                'maintenance_due_date' => now()->addMonths(1),
            ],
            [
                'name' => 'Packaging Line 1',
                'type' => 'packaging',
                'description' => 'Automated packaging line with labeling',
                'warehouse_id' => $mainWarehouse?->id,
                'location_details' => 'Floor 2, Bay D',
                'capacity_per_day' => 500,
                'capacity_unit' => 'units',
                'efficiency_percentage' => 92,
                'utilization_percentage' => 0,
                'cost_per_hour' => 35.00,
                'setup_time_minutes' => 45,
                'teardown_time_minutes' => 20,
                'minimum_batch_size' => 20,
                'maximum_batch_size' => 1000,
                'is_active' => true,
                'is_available' => true,
                'requires_operator' => true,
                'required_operators' => 3,
                'capabilities' => ['automated packaging', 'labeling', 'boxing', 'palletizing'],
                'certifications' => ['ISO 9001', 'FDA'],
                'maintenance_due_date' => now()->addMonths(2),
            ],
        ];

        foreach ($workCenters as $workCenterData) {
            WorkCenter::create($workCenterData);
        }

        $this->command->info('Work centers created successfully!');
    }
}
